### ISSUE TITLE
Bot not Working

### ISSUE THREAD

**Issue by DragonFBI** [RedditBot-Discord/redditbot#31]
Text Channel is marked as nsfw but the everytime something is posted, the bot says, "NSFW Content is only allowed in a NSFW Channel"

**Comment by bwac2517** [comment]
Try deleting the webhook and resubscribing it.

**Comment by DragonFBI** [comment]
how do I delete webhook and resubscribe

**Comment by bwac2517** [comment]
Edit the channel, click Integrations > Webhooks, And there you can find the webhook

Then make it again like you did originally

**Comment by DragonFBI** [comment]
ok ty, ill try that and let you know if it works

**Comment by DragonFBI** [comment]
do you know of a subreddit, that post often for me to test this

**Comment by bwac2517** [comment]
You can try super popular subreddits like dankmemes that get posted to almost every 30 seconds. But you probably want one that posts NSFW stuff often and I can't help you with that one :/

**Comment by DragonFBI** [comment]
well I tried and its saying the same thing

**Comment by bwac2517** [comment]
have you double checked the channel is set as NSFW?

**Comment by DragonFBI** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/80889227/118966768-8885be80-b92f-11eb-87e3-22dc87db9560.png)
I hope so

**Comment by bwac2517** [comment]
Well, What subreddit are you subscribing to so I can test this?

**Comment by DragonFBI** [comment]
r/hentai
fastest subreddit to test nsfw I can think of

**Comment by mrshmllow** [comment]
This has been fixed, I believe. Please tell me if it keeps happening :D

**Comment by mrshmllow** [comment]
#32
