### ISSUE TITLE
Bot stopped suddenly

### ISSUE THREAD

**Issue by vedant64** [RedditBot-Discord/redditbot#32]
Today at exactly 7:48 AM the bot stopped. It was working without any issues so far but dunno what happened suddenly.

**Comment by vedant64** [comment]
It's working sometimes and sometimes it does not update anything. 

Also, now if we create a channel (NSFW) and select a live update from a NSFW subreddit then it says ":NSFW Content is only allowed in a NSFW channel."

**Comment by mrshmllow** [comment]
Time zone? Also, last comment is known bug, #31 and I'll hopefully be able to look into it soon, I've been dedicating my time to education right now.

**Comment by mrshmllow** [comment]
Can you describe what exactly isn't working?

**Comment by vedant64** [comment]
Time Zone- GMT

Issue- I have created 4 different channels and any time of the day suddenly the live subscription for each channel stops. Like the bot stops working or something. And during this period if I try any command like to check Reddit profile or to subscribe to a new sub for live feeds, it shows me the error- "This interaction failed" 

When I keep trying the commands like after 5-10mins the bot starts working again and it does not show any error like above.

And it's completely fine. Take your time. Best of luck with your education.

**Comment by mrshmllow** [comment]
Thanks! Turns out nsfw part was a very very simple bug to fix.. It was a mistake from months ago

The **This interaction failed**, I have not been able to find a fix for, you just need to try the command again. Also if some streams stop working, you kinda just have to wait and it will catch up.

Make sure to tell me if it keeps happening after this :D

**Comment by vedant64** [comment]
Today at 5:28 AM bot stops. 

I tried command and it shows this- 

![image](https://user-images.githubusercontent.com/17106428/120092449-7296ab80-c130-11eb-8a25-d47a758db5d1.png)

After the command the bot starts to respond and I tried to add a subscription from NSFW sub and it shows this now-

![image](https://user-images.githubusercontent.com/17106428/120092462-8b9f5c80-c130-11eb-9bfe-d5a87921133f.png)

**Comment by mrshmllow** [comment]
is the channel nsfw?

**Comment by vedant64** [comment]
Edited the above comment

**Comment by mrshmllow** [comment]
sorry for such a long delay! I spent a hour debugging and turns out it was a pretty simple issue
(good thing my code automatically assumed to not send any nsfw!)
Anyway, you might have to delete and re add any streams.
